### ISSUE TITLE
Can´t open files

### ISSUE THREAD

**Issue by MarkusVa** [MarvinZeising/JWManagement#423]
**Describe the bug**
Hello,
we want to upload a pdf - after uploading the file we can´t open it anymore.
We also tried to download an existing file and want to upload it again. The same thing - we can´t open the file👎 

**To Reproduce**
1. Go to 'information'
2. Click on 'Dateien'
3. Nothing happens...

Thanks.
Best regards.

**Comment by levin1808** [comment]
Hi! Ich habe das gleiche Problem.

**Comment by MarvinZeising** [comment]
Hi, thanks for the input. (and that great "steps to reproduce")
This is a known problem which was handled in Discord (you might want to check there as well). There will be an email with more information for all project administrators in the next couple of days.

In short: There was an important database migration to a database provider that does not use older connection methods anymore. Since the library that we use to upload files in JW Management is stale for over 5 years now, it doesn't support new connection methods. The file upload would have to be implemented as a whole again.
Unfortunately, I don't have the time to do so. Therefore, the whole upload feature will be removed in the long run.

You can still upload files to the file upload provider of your choice (like OneDrive, Dropbox, etc.) and provide a link to the file in your information section.

Thank you for your understanding.
